[package]
name = "coincount"
version = "0.1.0"
authors = ["Riccardo Casatta <riccardo@casatta.it>"]

[dependencies]
data-encoding = "2.1.1"

[dependencies.plotlib]
git = "https://github.com/RCasatta/plotlib"
rev = "70c852e"
